### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Trip-kun** [cellux/zz#1]
When I try and install using your directions, this is what i get
I have installed all required packages
`triplapeeck@SKYNET:~$ # everything is stored under $ZZPATH                                                              triplapeeck@SKYNET:~$ ZZPATH=$HOME/zz                                                                                   triplapeeck@SKYNET:~$                                                                                                   triplapeeck@SKYNET:~$ # create package directory                                                                        triplapeeck@SKYNET:~$ mkdir -p $ZZPATH/src/github.com/cellux/zz                                                         triplapeeck@SKYNET:~$                                                                                                   triplapeeck@SKYNET:~$ # clone package                                                                                   triplapeeck@SKYNET:~$ cd $ZZPATH/src/github.com/cellux/zz                                                               triplapeeck@SKYNET:~/zz/src/github.com/cellux/zz$ git clone https://github.com/cellux/zz .                              Cloning into '.'...                                                                                                     remote: Enumerating objects: 1239, done.                                                                                remote: Total 1239 (delta 0), reused 0 (delta 0), pack-reused 1239                                                      Receiving objects: 100% (1239/1239), 443.71 KiB | 2.81 MiB/s, done.                                                     Resolving deltas: 100% (854/854), done.                                                                                 triplapeeck@SKYNET:~/zz/src/github.com/cellux/zz$                                                                       triplapeeck@SKYNET:~/zz/src/github.com/cellux/zz$ # compile, test, install                                              triplapeeck@SKYNET:~/zz/src/github.com/cellux/zz$ make                                                                  mkdir: created directory 'native'                                                                                       curl -skL -o native/LuaJIT-2.1.0-beta3.tar.gz http://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz                      tar xzf native/LuaJIT-2.1.0-beta3.tar.gz -C native                                                                      touch native/LuaJIT-2.1.0-beta3/.extracted                                                                              sed -i -r -e s/^(BUILDMODE)=.*/\1= static/ -e s/^(XCFLAGS)=.*/\1= -DLUAJIT_ENABLE_LUA52COMPAT/ native/LuaJIT-2.1.0-beta3/src/Makefile                                                                                                           make -C native/LuaJIT-2.1.0-beta3 clean amalg                                                                           make[1]: Entering directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3'                   make -C src clean                                                                                                       make[2]: Entering directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3/src'               make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         Makefile:268: *** Unsupported target architecture.  Stop.                                                               make[2]: Leaving directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3/src'                Makefile:162: recipe for target 'clean' failed                                                                          make[1]: *** [clean] Error 2                                                                                            make[1]: Leaving directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3'                    Makefile:5: recipe for target 'install' failed                                                                          make: *** [install] Error 2                                                                                             triplapeeck@SKYNET:~/zz/src/github.com/cellux/zz$ make test                                                             sed -i -r -e s/^(BUILDMODE)=.*/\1= static/ -e s/^(XCFLAGS)=.*/\1= -DLUAJIT_ENABLE_LUA52COMPAT/ native/LuaJIT-2.1.0-beta3/src/Makefile                                                                                                           make -C native/LuaJIT-2.1.0-beta3 clean amalg                                                                           make[1]: Entering directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3'                   make -C src clean                                                                                                       make[2]: Entering directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3/src'               make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         Makefile:268: *** Unsupported target architecture.  Stop.                                                               make[2]: Leaving directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3/src'                Makefile:162: recipe for target 'clean' failed                                                                          make[1]: *** [clean] Error 2                                                                                            make[1]: Leaving directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3'                    Makefile:5: recipe for target 'install' failed                                                                          make: *** [install] Error 2                                                                                             triplapeeck@SKYNET:~/zz/src/github.com/cellux/zz$ make install                                                          sed -i -r -e s/^(BUILDMODE)=.*/\1= static/ -e s/^(XCFLAGS)=.*/\1= -DLUAJIT_ENABLE_LUA52COMPAT/ native/LuaJIT-2.1.0-beta3/src/Makefile                                                                                                           make -C native/LuaJIT-2.1.0-beta3 clean amalg                                                                           make[1]: Entering directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3'                   make -C src clean                                                                                                       make[2]: Entering directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3/src'               make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         make[2]: gcc: Command not found                                                                                         Makefile:268: *** Unsupported target architecture.  Stop.                                                               make[2]: Leaving directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3/src'                Makefile:162: recipe for target 'clean' failed                                                                          make[1]: *** [clean] Error 2                                                                                            make[1]: Leaving directory '/home/triplapeeck/zz/src/github.com/cellux/zz/native/LuaJIT-2.1.0-beta3'                    Makefile:5: recipe for target 'install' failed                                                                          make: *** [install] Error 2                                                                                             triplapeeck@SKYNET:~/zz/src/github.com/cellux/zz$   `

**Comment by cellux** [comment]
Based on the error it seems to me that `gcc` cannot be found by the LuaJIT build.

What do you get if you run `gcc -v`? Here is the output on my machine:

```
[rb@pluto ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-pc-linux-gnu/9.1.0/lto-wrapper
Target: i686-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux32.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet --build=i686-pc-linux-gnu
Thread model: posix
gcc version 9.1.0 (GCC) 
```

You should get something similar.

If you get `gcc: command not found`, then you either have not installed gcc or it's not on the path.

**Comment by Trip-kun** [comment]
I got it to compile, thanks! Now im just sad i didn't read this tho
`The current version only supports Linux`

**Comment by Trip-kun** [comment]
I use windows :/
I was compiling through ubuntu for windows. Would there be any chance of being able to use this for windows, or no
